I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 274, in script
    kenadll " (reflective) Jan, I appreciate your understanding. I've realized that my navigation skills alone may not be enough. We should approach this as a team and seek professional guidance to find the perfect place."
Exception: Sayer 'kenadll' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 274, in script
    kenadll " (reflective) Jan, I appreciate your understanding. I've realized that my navigation skills alone may not be enough. We should approach this as a team and seek professional guidance to find the perfect place."
  File "C:\Users\Haha\Downloads\renpy-8.1.0-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Haha\Downloads\renpy-8.1.0-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'kenadll' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23051307
MindClashGame 1.0
Mon Jun 12 09:41:05 2023
